"""Add WechatUser model

Revision ID: 30a3a5a4e295
Revises: 
Create Date: 2025-07-26 21:59:56.914512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a3a5a4e295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_name', sa.String(length=64), nullable=False),
    sa.Column('wechat_id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wechat_users_wechat_id'), ['wechat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wechat_users_wechat_id'))

    op.drop_table('wechat_users')
    # ### end Alembic commands ###
