"""add_settlement_status_to_orders

Revision ID: 51023205e63e
Revises: b46ba16c57be
Create Date: 2025-07-27 19:56:16.598903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51023205e63e'
down_revision = 'b46ba16c57be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_orders')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_settled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('settle_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('settle_notes', sa.Text(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.alter_column('wechat_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_wechat_users_wechat_id'))
        batch_op.create_index(batch_op.f('ix_wechat_users_wechat_id'), ['wechat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_users_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wechat_users_phone'))
        batch_op.drop_index(batch_op.f('ix_wechat_users_wechat_id'))
        batch_op.create_index(batch_op.f('ix_wechat_users_wechat_id'), ['wechat_id'], unique=1)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('wechat_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('settle_notes')
        batch_op.drop_column('settle_time')
        batch_op.drop_column('is_settled')

    op.create_table('_alembic_tmp_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wechat_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wechat_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('order_info', sa.TEXT(), nullable=True),
    sa.Column('completion_time', sa.DATETIME(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('order_type_id', sa.INTEGER(), nullable=True),
    sa.Column('custom_fields', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_settled', sa.BOOLEAN(), nullable=False),
    sa.Column('settle_time', sa.DATETIME(), nullable=True),
    sa.Column('settle_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
