"""Add avatar and payment_qr_code fields to WechatUser

Revision ID: b46ba16c57be
Revises: 30a3a5a4e295
Create Date: 2025-07-26 22:09:23.253506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46ba16c57be'
down_revision = '30a3a5a4e295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_qr_code', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.drop_column('payment_qr_code')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
