"""remove settlement fields

Revision ID: remove_settlement_fields
Revises: 51023205e63e
Create Date: 2025-01-27 21:52:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_settlement_fields'
down_revision = '51023205e63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('settle_notes')
        batch_op.drop_column('settle_time')
        batch_op.drop_column('is_settled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_settled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('settle_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('settle_notes', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###